version: '2'
services:
  postgres:
    image: postgres
  gateway-socks:
    image: zoerepo/gateway-socks
    networks:
      - zoe
  zoe-api:
    image: zoerepo/zoe
    command: python3 zoe-api.py --debug --swarm ${SWARM_URL} --deployment-name compose --master-url tcp://zoe-master:4850 --dbuser postgres --dbhost postgres --dbname postgres
    ports:
      - "8080:5001"
    depends_on:
      - postgres
  zoe-master:
    image: zoerepo/zoe
    ports:
      - "4850:4850"
    volumes:
      - /etc/zoe:/etc/zoe
      - /opt/zoe-workspaces:/mnt/zoe-workspaces
    command: python3 zoe-master.py --debug --swarm ${SWARM_URL} --deployment-name compose --dbuser postgres --dbhost postgres --dbname postgres
    depends_on:
      - zoe-api
networks:
  zoe:
    driver: bridge
