apiVersion: v1
kind: Service
metadata:
  name: zoe-master-service
  namespace: fsdna
  labels:
    app: zoe-master
    task: test
spec:
  type: LoadBalancer
  ports:
  - name: zoe-master
    port: 4850
    targetPort: zoe-master
  selector:
    app: zoe-master
    task: test
